version: '3.5'
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.11
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24