apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo
spec:
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo
        image: josemokeni/react-todo
        ports:
        - containerPort: 80
